name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubunto-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cypress run
        uses: cypress-io/github-actions@v2